### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by janzeng**
The main changes are that there are now two CSS files that do not overlap. AcesUp.css now only applies when the screen is larger than 826 pixels. Mobile.css is only used when the screen is less 825 pixels.
The mobile view has been fixed so that the deal, score, and reset buttons are visible at the top, and the logo is only visible below the table if there is room on the screen. All of the block elements are also now flex boxes.
I made small changes to the HTML file adding in more tags so I could format the table easier.

### CODE REVIEW

**Comment by AntonSynytsiaOSU** [comment]
There are some styles that are not included in your PR, which are included in the current master branch, for example the .cardRed, .cardBlack, .cardMovable, .cardDefault. These are necessary for the styling.

**Comment by iamalotaibi** [comment]
I have checked it and it is neat! You could check it here https://aceuposu.herokuapp.com

**Comment by janzeng** [comment]
Ah, you’re right. I’ll fix it and make sure it includes the new styles tomorrow.

**Comment by AntonSynytsiaOSU** [comment]
Thank you!

**Comment by AntonSynytsiaOSU** [comment]
Although, if you want them all orange, that's fine too.

**Comment by iamalotaibi** [comment]
I have tested the app and it works just fine.

**Pull request merged**
